name: Build

on:
  workflow_dispatch:

jobs:
  graher:
    name: Native Build (Telegram)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: mkdir -p /home/Telegram && git clone https://github.com/DrKLO/Telegram /home/Telegram
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2
      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.4.7075529" --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/21.4.7075529" >> local.properties
      - name: Build Tg
        run: |
          ./gradlew assembleArm64Release
          echo "APK_FILE=$(find TMessagesProj/build/outputs/apk -name '*.apk')" >> $GITHUB_ENV
        working-directory: /home/Telegram
      - uses: actions/upload-artifact@v2
        name: Upload apk (arm64-v8a)
        with:
          name: Telegram-Arm64
          path: /home/Telegram/${{ env.APK_FILE }}
