name: jalanbuntu
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source run
    - name: Setup tmate session
      timeout-minutes: 340
      uses: mxschmitt/action-tmate@master
